# Generated by Django 5.2.6 on 2025-12-05 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100, verbose_name='Тип события')),
                ('event_date', models.DateField(verbose_name='Дата события')),
                ('reminder_days', models.PositiveSmallIntegerField(verbose_name='Дней до напоминания')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
        migrations.CreateModel(
            name='GreetingTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100, verbose_name='Тип события')),
                ('template_text', models.TextField(verbose_name='Текст шаблона')),
            ],
            options={
                'verbose_name': 'Шаблон поздравления',
                'verbose_name_plural': 'Шаблоны поздравлений',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('patronymic', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('gender', models.CharField(max_length=10, verbose_name='Пол')),
                ('workplace', models.CharField(max_length=200, verbose_name='Место работы/учёбы')),
                ('position', models.CharField(max_length=150, verbose_name='Должность')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Заметки')),
            ],
            options={
                'verbose_name': 'Человек',
                'verbose_name_plural': 'Люди',
            },
        ),
        migrations.CreateModel(
            name='Greeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата генерации')),
                ('greeting_text', models.TextField(verbose_name='Текст поздравления')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Отправлено')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notebook.event', verbose_name='Событие')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notebook.greetingtemplate', verbose_name='Шаблон')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notebook.person', verbose_name='Человек')),
            ],
            options={
                'verbose_name': 'Поздравление',
                'verbose_name_plural': 'Поздравления',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notebook.person', verbose_name='Человек'),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notebook.person', verbose_name='Человек')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(max_length=100, verbose_name='Тип отношений')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person', to='notebook.person', verbose_name='Человек')),
                ('related_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_person', to='notebook.person', verbose_name='Связанный человек')),
            ],
            options={
                'verbose_name': 'Отношение',
                'verbose_name_plural': 'Отношения',
            },
        ),
    ]
